# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTRlNmYyNmZmNWRmMTQxOGVhMWE5MDlmNmZhNTFjZjI2MjdkY2VhMjRiM2U1MTU2YzQ4NGY3OTgzMzg3Mzc1MDQ0OWY5OGI2ZTNiMzMwMjc0ODc3NTdkZDRkNzJkZWE5M2VkNmJlMmE4ZTA5NDlmNDIwY2RiNjA0MDg3MzUwN2Y=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
